import Head from "next/head";
import React, { useEffect, useState } from "react";
import Axios from "axios";
import { useRouter } from "next/router";

import { Button, Form, FormCheck } from "react-bootstrap";
import { wrapper } from "../../redux/store2";

import { useSelector } from "react-redux";

export default function AddBootCamp({ props }) {
  //const getUser = useSelector(selectUser);
  //console.log("getUser", getUser.userArray);
  const resetValue = {
    title: "",
  };

  const router = useRouter();
  const [form, setForm] = useState(resetValue);

  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value,
    });
  };

  const addData = async (e) => {
    e.preventDefault();
    const { title } = form;

    const result = await Axios(`http://localhost:4200/api/camp/add`, {
      //axios는 무조건 풀로 주소를 넣어야 한다.
      method: "POST",
      data: {
        title: title,
      },
      headers: {
        "Content-Type": "application/json",
      },
    })
      .then((res) => {
        console.log(res.headers);
      })
      .catch((err) => {
        console.log(err);
        router.push({ pathname: "/404", query: { message: err } });
      });
    setForm(resetValue);
  };

  // useEffect(() => {
  //   readData();
  // }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container" id="add-data">
        <h2 className="text-center mt-5 ">ADD BOOTCAMP</h2>
        <div className="d-flex justify-content-center mt-3">
          <Form style={{ width: "420px" }} onSubmit={addData}>
            <Form.Group controlId="title">
              <Form.Label>title</Form.Label>
              <Form.Control
                name="name"
                value={form.title}
                onChange={handleChange}
              />
            </Form.Group>
            <input type="submit" value="register" className="btn btn-primary" />
          </Form>
        </div>
      </div>
    </div>
  );
}

// export const getStaticProps = wrapper.getStaticProps(async (context) => {
//   const rslt = await Axios(`http://localhost:4200/api/data/read`, {
//     method: "GET",
//   });
//   context.store.dispatch(UserSuccess(rslt.data));
// });
