import Head from "next/head";
import React, { useEffect, useState } from "react";
import Axios from "axios";
import { useRouter } from "next/router";

import { Button, Form, FormCheck } from "react-bootstrap";
import { wrapper } from "../../redux/store";

import { useSelector } from "react-redux";
import { CommonService } from "../api/services/common-service";
import { State } from "../../redux/slices";
import { IAuthInfo } from "../../src/interface/auth-interface";

export default function AddBootCamp({ props }) {
  //const getUser = useSelector(selectUser);
  //console.log("getUser", getUser.userArray);
  const resetValue = {
    content: "",
  };

  const router = useRouter();
  const [form, setForm] = useState(resetValue);
  const [campList, setCampList] = useState();
  const [reviews, setViews] = useState();

  const user = useSelector((state: State) => state.users).userInfo;

  const bringToken = useSelector((state: { auth: IAuthInfo }) => state.auth);
  console.log("mypage user", user);

  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value,
    });
  };

  const findMyCampAPI = async () => {
    const send = {
      userId: user.id,
    };
    const rlst = await CommonService.instance.findCampList(
      send,
      bringToken.token
    );
    console.log("rlst", rlst);
  };
  useEffect(() => {
    findMyCampAPI();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container" id="add-data">
        <h2 className="text-center mt-5 ">My-Page</h2>
        <div className="d-flex">
          <div className="d-flex justify-content-center mt-3">
            <h4>My BootCamp Study</h4>
            <ul></ul>
          </div>
          <div className="d-flex justify-content-center mt-3">
            <h4>My Reviews</h4>
            <ul></ul>
          </div>
        </div>
      </div>
    </div>
  );
}

// export const getStaticProps = wrapper.getStaticProps(async (context) => {
//   const rslt = await Axios(`http://localhost:4200/api/data/read`, {
//     method: "GET",
//   });
//   context.store.dispatch(UserSuccess(rslt.data));
// });
