import Head from "next/head";
import React, { useEffect, useState } from "react";
import Axios from "axios";
import { useRouter } from "next/router";

import { Button, Form } from "react-bootstrap";
import wrapper from "./_app";
import { useDispatch, useSelector } from "react-redux";
import { putUserInfo } from "../redux/feature/auth";
import axios from "axios";
import { selectAuth } from "../redux/feature/auth/index";

export default function Home() {
  const dispatch = useDispatch();
  const getKeycloak = useSelector(selectAuth);

  const [name, setName] = useState("");

  const handleChange = (e) => {
    e.preventDefault();
    setName(e.target.value);
  };
  const loginName = async (e) => {
    console.log(name);
    e.preventDefault();
    await axios(`http://localhost:4200/api/auth/login`, {
      method: "POST",
      data: {
        name: name,
      },
    })
      .then((rslt) => {
        console.log("success login inner");
        console.log(rslt);
        dispatch(putUserInfo(rslt.data));
      })
      .catch((err) => console.log(err));

    //console.log(getKeycloak.keycloak);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mt-3">
        <Form
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            height: "100vh",
          }}
          onSubmit={loginName}
        >
          <Form.Group>
            <Form.Label>이름</Form.Label>
            <Form.Control name="name" value={name} onChange={handleChange} />
            <input type="submit" value="데이터확인" />
          </Form.Group>
        </Form>
      </div>
    </div>
  );
}
