import Head from 'next/head';
import React, { ReactNode, useEffect, useState } from 'react';

import { useDispatch, useSelector } from 'react-redux';
import { RootState } from '../redux/store3';
import { KeycloakInstance } from 'keycloak-js';

export default function Home() {
  const getKeycloak = useSelector<RootState, KeycloakInstance>((state) => state.users.keycloakInfo);
  //console.log(getKeycloak.tokenParsed.preferred_username);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mt-3">
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            height: '100vh',
          }}
        >
          <h3>{getKeycloak && getKeycloak.tokenParsed.preferred_username}님 안녕하세요</h3>
        </div>
      </div>
    </div>
  );
}
